global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#aleksandr_lebedev'