version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: ${USER_NAME}/ui
#    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net
  post:
    image: ${USER_NAME}/post
#    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - front_net
      - back_net
  comment:
    image: ${USER_NAME}/comment
#    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - front_net
      - back_net 
  
volumes:
  post_db:

  prometheus_data:

networks:
  front_net:

  back_net:

