version: '3.3'
services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks: 
    - front_net
    - back_net 

  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
    - front_net
    - back_net 

  elasticsearch:
    image: elasticsearch:7.3.1
    expose:
      - 9200
    container_name: elasticsearch  
    ports:
      - "9200:9200"
    networks:
      - front_net
      - back_net 
    environment:
#      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}        
      - discovery.type=single-node
      - transport.host=localhost
      - transport.tcp.port=9300
      - http.port=9200
      - http.host=0.0.0.0
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:7.3.1
    ports:
      - "5601:5601"
    networks:
      - front_net
      - back_net 
networks:
  front_net:

  back_net:

...
